name: toty
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  launcher_assist: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

