name: toty
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  launcher_assist: ^1.0.4
  path_provider: ^0.4.1
  flutter_redux: "^0.5.0"

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

